### ISSUE TITLE
outdated encoder

### ISSUE THREAD

**Issue by lmcmgig** [foliojs/brotli.js#21]
The encoder, in some scenarios, produce an incompatible output for the brotli 1.0.4 decoder C version.  Need a lib upgrade and rebuild?

Same data on the C version works correctly.

**Comment by alrra** [comment]
> Need a lib upgrade and rebuild?

Friendly ping @devongovett 👋

**Comment by devongovett** [comment]
Yes. The encoder is compiled with emscripten so should be fairly easy unless they changed the API dramatically. The decoder is hand ported, so that will be harder to update.

**Comment by devongovett** [comment]
encoder is updated by https://github.com/foliojs/brotli.js/pull/51
