### ISSUE TITLE
Deprecate in favor of iltorb

### ISSUE THREAD

**Issue by DanielRuf** [foliojs/brotli.js#27]
There did not much happen since the last release

https://github.com/foliojs/brotli.js/compare/v1.3.2...master

But I have seen much slower compression compared to the iltorb package.
I think we should focus on one package (iltorb) and deprecate this one as the other one gets regular updates, has much better performance and is actively maintained.

**Comment by devongovett** [comment]
iltorb doesn't work in browser environments as far as I am aware - it's a native C++ package for node only.

As for maintenance, I'd be happy for people to help with that. Let me know if you're interested.

**Comment by Janaka-Steph** [comment]
NPM iltorb page says: "The zlib module provides APIs for brotli compression/decompression starting with Node.js v10.16.0, please use it over iltorb"

**Comment by DanielRuf** [comment]
@Janaka-Steph right, maybe this can be wrapped somehow but I think there are already such modules.
