### ISSUE TITLE
Unable to deploy in the browser:  "ReferenceError: Browser is not defined"

### ISSUE THREAD

**Issue by Pomax** [foliojs/brotli.js#28]
Running `npm install brotli`, and then running `browserify index.js -o brotli.browser.js -s Brotli` yields a file that cannot be used in the browser, citing:

```
[warning] TypeError: asm.js type error: Disabled by debugger
[error] ReferenceError: Browser is not defined (brotli.browser.js:703:191)
```

**Comment by ethernomad** [comment]
https://github.com/foliojs/brotli.js/issues/20

**Comment by devongovett** [comment]
This doesn't exist anymore after updating emscripten https://github.com/foliojs/brotli.js/pull/51

**Comment by Wunsz** [comment]
@devongovett since that is resolved can we have a NPM release with that fix?

**Comment by devongovett** [comment]
Yeah sorry it's a bit blocked at the moment. The change to WASM makes it async which would be a huge breaking change. Still thinking about what to do there...

**Comment by Pomax** [comment]
should be fine as long as you bump the major version number? (those signal backward incompatible changes)

**Comment by elshapovalov** [comment]
I try to run [Uniswap example](https://github.com/Uniswap/examples/tree/main/v3-sdk/swap-and-add-liquidity) and always get error in browser console:
**Uncaught ReferenceError: Browser is not defined
    at Va (encode.js:49:1)**
  
 Can anybody help me?

**Comment by Pomax** [comment]
@ElShapovalov you probably want to file that over on https://github.com/Uniswap/examples/issues?

**Comment by elshapovalov** [comment]
@Pomax no, becouse error in file "encode.js" packege "brotli".
What is object the "Browser" with function "T"?

**Comment by Pomax** [comment]
That's still something for Uniswap to look into first. Just because you get the error in the brotli package doesn't mean the _problem_ is with the brotli package, it's far more likely the problem is that the Uniswap example code, or a dependency that they're using that in turn relies on brotli.js, is calling the wrong functions, or is calling the right functions but without having properly initialized things.

That's something for them to try to fix first by examining their code and updating it to work the way it's supposed to, which they can't do unless you file an issue on their issue tracker that explains the exact steps you took, and which commands you ran, to get to the error that you're seeing.

And if _they_ conclude that they're doing everything right, that's the right time to file a new issue here (unless they're not directly using brotli.js, in which case that issue should get filed on the issue tracker for the dependency that does).

**Comment by elshapovalov** [comment]
@Pomax thanks, i understand!
