### ISSUE TITLE
npmjs release

### ISSUE THREAD

**Issue by unicomp21** [foliojs/brotli.js#30]
Any plans to update npmjs w/ the latest?

**Comment by bayssmekanique** [comment]
@foliojs, could we get a release of the `master` branch? It contains the `fs` removal merge which fixes browser utilization.

**Comment by Xal3ph** [comment]
@devongovett , may we please get a new release of this project on npm?  Thank you in advance!

**Comment by devongovett** [comment]
Yeah sorry about that. Done.
