### ISSUE TITLE
compress returns null

### ISSUE THREAD

**Issue by ekwoka** [foliojs/brotli.js#36]
I'm passing in a buffer and getting null

standalone or not, it returns null

```js
const compressed = compress(buffer);
const compressed2 = brotli.compress(buffer);
```

The buffer logs as a bugger before this, then no errors or anything but returns null

**Comment by dgandhi1993** [comment]
This seems to be an issue with the latest Node versions. 
I am not experiencing any problems with v12.x but with v16.15.0 this gives null.

Has anyone found a fix for this?

**Comment by devongovett** [comment]
Might work with the updated version https://github.com/foliojs/brotli.js/pull/51

**Comment by wojtekmaj** [comment]
@devongovett Do you have plans on releasing this fix? :)
