### ISSUE TITLE
Sending compressed html content through brotli not working

### ISSUE THREAD

**Issue by The-Lord-of-Owls** [foliojs/brotli.js#44]
I have tried with Content-Type: br and Content-Type: text/html, aswell as both with and without the Accept-Encoding: br header.

Ever attempt has resulted in the browser only displaying the compressed html as a string without decompressing it at all. Happens in both latest version of chrome and firefox.

```js
const pageFormat = brotli.compress( fs.readFileSync( './html/index.html', { encoding: 'utf8' } ) )

app.get( '/', ( req, res ) => {
	res.setHeader( 'Content-Type', 'text/html' )
	res.setHeader( 'Accept-Encoding', 'br' )
	res.end( pageFormat )
} )
```

**Comment by nand2** [comment]
You should use `Content-Encoding` instead of `Accept-Encoding` in the response.

**Comment by The-Lord-of-Owls** [comment]
Late reply but thank you!
